/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ApiRagRouteImport } from './routes/api/rag'
import { Route as ApiRagBenchmarkRouteImport } from './routes/api/rag-benchmark'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagRoute = ApiRagRouteImport.update({
  id: '/api/rag',
  path: '/api/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagBenchmarkRoute = ApiRagBenchmarkRouteImport.update({
  id: '/api/rag-benchmark',
  path: '/api/rag-benchmark',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/team': typeof TeamRoute
  '/api/rag': typeof ApiRagRoute
  '/api/rag-benchmark': typeof ApiRagBenchmarkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/team': typeof TeamRoute
  '/api/rag': typeof ApiRagRoute
  '/api/rag-benchmark': typeof ApiRagBenchmarkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/team': typeof TeamRoute
  '/api/rag': typeof ApiRagRoute
  '/api/rag-benchmark': typeof ApiRagBenchmarkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/team' | '/api/rag' | '/api/rag-benchmark'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/team' | '/api/rag' | '/api/rag-benchmark'
  id: '__root__' | '/' | '/team' | '/api/rag' | '/api/rag-benchmark'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamRoute: typeof TeamRoute
  ApiRagRoute: typeof ApiRagRoute
  ApiRagBenchmarkRoute: typeof ApiRagBenchmarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag': {
      id: '/api/rag'
      path: '/api/rag'
      fullPath: '/api/rag'
      preLoaderRoute: typeof ApiRagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag-benchmark': {
      id: '/api/rag-benchmark'
      path: '/api/rag-benchmark'
      fullPath: '/api/rag-benchmark'
      preLoaderRoute: typeof ApiRagBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamRoute: TeamRoute,
  ApiRagRoute: ApiRagRoute,
  ApiRagBenchmarkRoute: ApiRagBenchmarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
